services:
  marzban:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    env_file: .env.dev
    ports:
      - "8000:8080"
    volumes:
      - ./.marzban/var/lib/marzban:/var/lib/marzban

  proxy:
    image: alpine/socat
    restart: always
    network_mode: "service:marzban"
    command: tcp-listen:8080,fork,reuseaddr tcp-connect:127.0.0.1:8000
    depends_on:
      - marzban
