"""update_user_client

Revision ID: 07a653f488a9
Revises: 64eb4e7725e1
Create Date: 2026-04-07 19:20:28.982764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07a653f488a9'
down_revision = '64eb4e7725e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'name',
                    existing_type=mysql.VARCHAR(
                        charset='utf8mb4', collation='utf8mb4_bin', length=256),
                    type_=sa.String(
                        length=256, collation='utf8mb4_unicode_ci'),
                    existing_nullable=True)
    # op.add_column('user_clients', sa.Column('hwid', sa.String(length=128), nullable=False))
    # op.add_column('user_clients', sa.Column(
    #     'device_model', sa.String(length=128), nullable=False))
    # op.add_column('user_clients', sa.Column(
    #     'device_os', sa.String(length=64), nullable=False))
    # op.add_column('user_clients', sa.Column(
    #     'app_version', sa.String(length=32), nullable=False))
    # op.drop_index('uq_user_client', table_name='user_clients')
    # op.create_unique_constraint(
    #     'uq_user_client_hwid', 'user_clients', ['user_id', 'hwid'])
    # op.drop_constraint('user_clients_ibfk_1',
    #                    'user_clients', type_='foreignkey')
    # op.create_foreign_key(None, 'user_clients', 'users', ['user_id'], ['id'])
    # op.alter_column('users', 'username',
    #                 existing_type=mysql.VARCHAR(
    #                     charset='utf8mb4', collation='utf8mb4_bin', length=34),
    #                 type_=sa.String(length=34, collation='utf8mb4_unicode_ci'),
    #                 existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
                    existing_type=sa.String(
                        length=34, collation='utf8mb4_unicode_ci'),
                    type_=mysql.VARCHAR(charset='utf8mb4',
                                        collation='utf8mb4_bin', length=34),
                    existing_nullable=True)
    op.drop_constraint(None, 'user_clients', type_='foreignkey')
    op.create_foreign_key('user_clients_ibfk_1', 'user_clients', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_client_hwid', 'user_clients', type_='unique')
    op.create_index('uq_user_client', 'user_clients', [
                    'user_id', 'user_agent'], unique=True)
    op.drop_column('user_clients', 'app_version')
    op.drop_column('user_clients', 'device_os')
    op.drop_column('user_clients', 'device_model')
    op.drop_column('user_clients', 'hwid')
    op.alter_column('nodes', 'name',
                    existing_type=sa.String(
                        length=256, collation='utf8mb4_unicode_ci'),
                    type_=mysql.VARCHAR(charset='utf8mb4',
                                        collation='utf8mb4_bin', length=256),
                    existing_nullable=True)
    # ### end Alembic commands ###
