"""update_user_client

Revision ID: 34f372cb132e
Revises: 07a653f488a9
Create Date: 2026-04-07 21:06:26.250150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34f372cb132e'
down_revision = '07a653f488a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_clients', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=True)
    op.alter_column('user_clients', 'device_model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
    op.alter_column('user_clients', 'device_os',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('user_clients', 'app_version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True)
    op.create_unique_constraint('uq_user_client_hwid', 'user_clients', ['user_id', 'hwid'])
    op.drop_constraint('user_clients_ibfk_1', 'user_clients', type_='foreignkey')
    op.create_foreign_key(None, 'user_clients', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=34),
               type_=sa.String(length=34, collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=34, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=34),
               existing_nullable=True)
    op.drop_constraint(None, 'user_clients', type_='foreignkey')
    op.create_foreign_key('user_clients_ibfk_1', 'user_clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_client_hwid', 'user_clients', type_='unique')
    op.alter_column('user_clients', 'app_version',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False)
    op.alter_column('user_clients', 'device_os',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.alter_column('user_clients', 'device_model',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)
    op.alter_column('user_clients', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=False)
    # ### end Alembic commands ###
