"""add_user_ips_table_and_device_limit

Revision ID: 4ff5a34319fe
Revises: 2b231de97dc3
Create Date: 2026-03-25 21:59:11.056575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ff5a34319fe'
down_revision = '2b231de97dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip', name='uq_user_ip')
    )
    op.create_index(op.f('ix_user_ips_id'), 'user_ips', ['id'], unique=False)
    op.create_index(op.f('ix_user_ips_user_id'), 'user_ips', ['user_id'], unique=False)
    op.alter_column('exclude_inbounds_association', 'inbound_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
               nullable=True)
    op.alter_column('hosts', 'alpn',
               existing_type=mysql.ENUM('h3', 'h3,h2', 'h3,h2,http/1.1', 'none', 'h2', 'http/1.1', 'h2,http/1.1', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('none', 'h3', 'h2', 'http/1.1', 'h3,h2,http/1.1', 'h3,h2', 'h2,http/1.1', name='proxyhostalpn'),
               existing_nullable=False)
    op.alter_column('template_inbounds_association', 'inbound_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
               nullable=True)
    op.add_column('users', sa.Column('device_limit', sa.Integer(), nullable=False))
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('on_hold', 'active', 'limited', 'expired', 'disabled', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('active', 'disabled', 'limited', 'expired', 'on_hold', name='userstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('active', 'disabled', 'limited', 'expired', 'on_hold', name='userstatus'),
               type_=mysql.ENUM('on_hold', 'active', 'limited', 'expired', 'disabled', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('users', 'device_limit')
    op.alter_column('template_inbounds_association', 'inbound_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
               nullable=False)
    op.alter_column('hosts', 'alpn',
               existing_type=sa.Enum('none', 'h3', 'h2', 'http/1.1', 'h3,h2,http/1.1', 'h3,h2', 'h2,http/1.1', name='proxyhostalpn'),
               type_=mysql.ENUM('h3', 'h3,h2', 'h3,h2,http/1.1', 'none', 'h2', 'http/1.1', 'h2,http/1.1', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('exclude_inbounds_association', 'inbound_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
               nullable=False)
    op.drop_index(op.f('ix_user_ips_user_id'), table_name='user_ips')
    op.drop_index(op.f('ix_user_ips_id'), table_name='user_ips')
    op.drop_table('user_ips')
    # ### end Alembic commands ###
