"""add_user_clients_remove_user_ips

Revision ID: 64eb4e7725e1
Revises: 4ff5a34319fe
Create Date: 2026-03-26 02:35:31.292276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64eb4e7725e1'
down_revision = '4ff5a34319fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Создаём новую таблицу
    op.create_table('user_clients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_agent', sa.String(length=512), nullable=False),
                    sa.Column('first_seen', sa.DateTime(), nullable=False),
                    sa.Column('last_seen', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'user_agent', name='uq_user_client')
                    )
    op.create_index(op.f('ix_user_clients_id'), 'user_clients', ['id'], unique=False)
    op.create_index(op.f('ix_user_clients_user_id'), 'user_clients', ['user_id'], unique=False)

    # 2. Удаляем user_ips: сначала FK, потом индексы, потом таблицу
    op.drop_constraint('user_ips_ibfk_1', 'user_ips', type_='foreignkey')
    op.drop_index('ix_user_ips_id', table_name='user_ips')
    op.drop_index('ix_user_ips_user_id', table_name='user_ips')
    op.drop_index('uq_user_ip', table_name='user_ips')
    op.drop_table('user_ips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=34, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=34),
               existing_nullable=True)
    op.alter_column('nodes', 'name',
               existing_type=sa.String(length=256, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=256),
               existing_nullable=True)
    op.create_table('user_ips',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('last_seen', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_ips_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_user_ip', 'user_ips', ['user_id', 'ip'], unique=True)
    op.create_index('ix_user_ips_user_id', 'user_ips', ['user_id'], unique=False)
    op.create_index('ix_user_ips_id', 'user_ips', ['id'], unique=False)
    op.drop_index(op.f('ix_user_clients_user_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_id'), table_name='user_clients')
    op.drop_table('user_clients')
    # ### end Alembic commands ###
